.\" Man Page for bluetoothService 
.TH BluetoothService 1 "August 05, 2020"
.SH "NAME"
bluetoothService \- command line binary for bluetoothService
.SH "SYNOPSIS"
.B bluetoothService
.SH "DESCRIPTION"
.B bluetoothService
Manual for UKUI desktop environment
 A lightweight Bluetooth Service based on libkf5bluezqt6
.TP
\fB --user\fR
The user to be anthenticated.
.TP
\fB --device\fR
The device for authentication.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
http://github.com/ukui/ukui-bluetooth/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by
tangguang <tangguang@kylinos.cn> (2020)

